# Generated by Django 5.1.5 on 2025-02-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanapplication',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='email',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='phone_number',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
