# Generated by Django 5.1.5 on 2025-02-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_rename_submitted_at_loanapplication_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
    ]
